#docker compose file used to launch the container with the dana services that serves webpages
version: '3'
services:
  dana-web-service:
    image: dana-web-service:latest
    build: ./linux
    ports:
        - 5000:2018
    restart: always
# this uses a docker file to pull an image of ubuntu with dana installed on it and puts the
# web page serving services on this container  